473: миграция на образ Alpine
rbkmoney/erlang_capi_pcidss_v1 pull request #25
Opened 2020-11-30 16:02 UTC by dinama

- обновлены образы сборки
- обновлен build_utils

2020-11-30 16:38 UTC, kpy3 requested changes
Кажется тащить erts и его исходники в образ не лучшая идея, они там итак уже есть

2020-11-30 19:12 UTC, kpy3 commented on rebar.config
> +            {include_erts, false},
исходники в проде тоже не нужны

2020-11-30 19:34 UTC, dinama commented on rebar.config
> +            {include_erts, false},
> исходники в проде тоже не нужны

там на верхнем уровне `{include_src, false}` - должно наследоваться-же

2020-11-30 19:38 UTC, kpy3 commented on rebar.config
> +            {include_erts, false},
А точно наследуется?

2020-11-30 19:41 UTC, dinama commented on rebar.config
> +            {include_erts, false},
> А точно наследуется?

да. но я думаю это наверно по-ошибке там вставили disable, переместил в prod, а там убрал (стало поведение по-умолчанию). А в capi_v1 было включено в prod почему-то.

2020-11-30 21:03 UTC, artbrunov approved these changes

2020-12-01 06:55 UTC, kpy3 approved these changes

2020-12-01 07:22 UTC, merged