upgrade world
rbkmoney/erlang_capi_pcidss_v1 pull request #29
Opened 2021-01-21 18:49 UTC by dinama

- image
- deps
- dialyzer
- elvis

2021-01-22 10:41 UTC, kpy3 requested changes

2021-01-22 10:41 UTC, kpy3 commented on Makefile
> +BUILD_IMAGE_TAG := 1333d0926b203e00c47e4fad7e10d2252a020305
Такого нет

2021-01-22 10:41 UTC, kpy3 commented on Makefile
> +	elvis rock -V
Кажется этот флаг лишний

2021-01-22 10:41 UTC, kpy3 commented on rebar.config
> +                {git, "git@github.com:rbkmoney/logger_logstash_formatter.git", {branch, master}}},
думаю тут стоит зафиксировать версию, как в, например, [тут](https://github.com/rbkmoney/erlang_capi_pcidss_v2/blob/master/rebar.config#L152). Для минимизации рисков получить невоспроизводимый билд как минимум.

2021-01-22 10:41 UTC, kpy3 commented on rebar.config
> +    {erlfmt, "0.9.0"}
👍

2021-01-22 15:49 UTC, dinama commented on Makefile
> +BUILD_IMAGE_TAG := 1333d0926b203e00c47e4fad7e10d2252a020305
> Такого нет

есть. я проверил.

2021-01-22 15:49 UTC, dinama commented on Makefile
> +	elvis rock -V
> Кажется этот флаг лишний

раньше без этого флага elvis выводил трассировку проверяемых файлов, а теперь не выводит. добавление этого флага делает как раньше.

2021-01-22 15:49 UTC, dinama commented on rebar.config
> +                {git, "git@github.com:rbkmoney/logger_logstash_formatter.git", {branch, master}}},
действтельно, зависимости из профилей почему-то не включаются в lock. перенес в основные зависимости - как в других сервисах. даже демо-конфиг содержит этот форматировщик.

2021-01-27 10:34 UTC, kpy3 commented on Makefile
> +	elvis rock -V
OK

2021-01-27 10:37 UTC, kpy3 commented on rebar.config
> -            {logger_logstash_formatter,
А почему это исчезло?

2021-01-27 10:55 UTC, dinama commented on rebar.config
> -            {logger_logstash_formatter,
> А почему это исчезло?

не исчезло. how_are_you&logger_stash перенес в основные зависимости, для возможности заморозки версии. как сделано в других проектах. recon остался.

2021-01-27 10:59 UTC, kpy3 commented on rebar.config
> -            {logger_logstash_formatter,
это, как и рекон, рантайм зависимости, и замораживать их надо так же как и recon

2021-01-27 16:21 UTC, dinama commented on rebar.config
> -            {logger_logstash_formatter,
> это, как и рекон, рантайм зависимости, и замораживать их надо так же как и recon

перенёс

2021-01-28 11:41 UTC, vulnbe submitted a review, later dismissed

2021-01-29 12:20 UTC, kpy3 commented on rebar.config
> +    {binbase_proto, {git, "git@github.com:rbkmoney/binbase-proto.git", {branch, "master"}}},
Давай может сразу поменяем?

2021-01-29 12:21 UTC, kpy3 commented on rebar.config
> -            {logger_logstash_formatter,
Я так и не понял как будет в итоге? 🤔В capi_v1 рантайм -зависимости тут, а тут она среди общих зависимостей. Может уже как-то одинаково везде?

2021-01-29 15:30 UTC, kpy3 submitted a review, later dismissed

2021-02-01 07:16 UTC, kpy3 approved these changes

2021-02-01 09:07 UTC, vulnbe approved these changes

2021-02-01 09:42 UTC, merged